#!/bin/bash

set -e

entrypoint="/bin/bash"
arg=""

if [ -z "$build_arch" ] ; then
  echo "arch?"
  exit 1
fi

if [ -z "$build_package" ] ; then
  echo "package?"
  exit 1
fi

if [ -z "$action" ] ; then
  echo "action?"
  exit 1
fi

if [ "$build_arch" = "i586" ] ; then
  arg="$entrypoint"
  entrypoint="linux32"
  platform="linux/386"
  shortarch=386
elif [ "$build_arch" = "x86_64" ] || [ "$build_arch" = "amd64" ] ; then
  build_arch=x86_64
  platform="linux/amd64"
  shortarch=amd64
elif [ "$build_arch" = "arm" ] ; then
  platform="linux/arm/v7"
  shortarch=arm
else
  echo "Unknown arch $build_arch"
  exit 1
fi

slackversion=15.0
repo=SBo
sbo=/var/lib/jenkins/caches/slackrepo/$slackversion/$repo
slackrepo=/var/lib/slackrepo/$repo
slackrepo_image=aclemons/slackrepo:slack-$slackversion

logs="$sbo/logs-$build_arch"

git="$(pwd)"

docker pull --quiet --platform "$platform" "$slackrepo_image"
docker tag "$slackrepo_image" "$slackrepo_image"-$shortarch
docker image rm "$slackrepo_image"

docker run --rm --cap-add SYS_ADMIN --platform "$platform" --entrypoint "$entrypoint" -v "$sbo":"$slackrepo" -v "$logs":/var/log/slackrepo -v "$git":"$slackrepo/slackbuilds" "$slackrepo_image"-$shortarch $arg -l -c "rm -rf $slackrepo/.lock && rm -rf $slackrepo/source/$build_package"

if [ "$action" = "build" ] ; then
  {
    echo "# buildpkg $build_arch $build_package"
    echo '```'
    docker run --rm --cap-add SYS_ADMIN --platform "$platform" --entrypoint "$entrypoint" -v "$sbo":"$slackrepo" -v "$logs":/var/log/slackrepo -v "$git":"$slackrepo/slackbuilds" "$slackrepo_image"-$shortarch $arg -l -c "git config --global --add safe.directory /var/lib/slackrepo/SBo/slackbuilds && slackrepo build $build_package"
    echo '```'
  } 2>&1 | sed 's/slackrepo/repo/g' | sed '/mount: /d' | sed "/^:-)/s/^:-) \(.*\) (-:$/✅ \1 ✅/" | sed "/^:-(/s/^:-( \(.*\) )-:$/⛔️ \1 ⛔️/" | tee ../build_results

  if grep -q "⛔️ $build_package" ../build_results > /dev/null 2>&1 ; then
    {
      echo ""
      echo "## Snipped Build Failure"
      echo ""
      echo "<details>"
      echo ""
      echo '```'
      docker run --rm --cap-add SYS_ADMIN --platform "$platform" --entrypoint "$entrypoint" -v "$sbo":"$slackrepo" -v "$logs":/var/log/slackrepo -v "$git":"$slackrepo/slackbuilds" "$slackrepo_image"-$shortarch $arg -l -c "cat /var/log/slackrepo/SBo/$build_package/build.log" | sed 's/slackrepo/repo/g' | tail -n 250
      echo '```'
      echo ""
      echo "</details>"
    } | tee -a ../build_results
  fi
fi

if [ "$action" = "lint" ] || grep -q "✅ $build_package" ../build_results > /dev/null 2>&1 ; then
  docker pull --quiet --platform "$platform" aclemons/sbo-maintainer-tools:latest-$slackversion
  docker tag aclemons/sbo-maintainer-tools:latest-$slackversion aclemons/sbo-maintainer-tools:latest-$slackversion-$shortarch
  docker image rm aclemons/sbo-maintainer-tools:latest-$slackversion

  if ls "$slackrepo/packages/$slackversion/$build_arch/$build_package/"*.dep > /dev/null 2>&1 ; then
    echo ""
  fi

  mkdir -p ../helper
  cat << EOF > ../helper/run_lint
#!/bin/bash

set -e
mkdir -p /tmp/SBo
depfiles=($slackrepo/packages/$slackversion/$build_arch/$build_package/*.dep)
[ "\${#depfiles[@]}" -ge 2 ] && exit 1
if [ -e "\${depfiles[0]}" ] ; then
  cat "\${depfiles[0]}" | while read -r dep ; do
    echo "Installing dependency: \$dep"
    dep_dir="\$(find $slackrepo/packages/$slackversion/$build_arch/ -name "\$dep" -type d)"
    TERSE=0 installpkg "\$dep_dir/*t?z"
    echo ""
  done
fi

sbopkglint $slackrepo/packages/$slackversion/$build_arch/$build_package/*t?z
EOF
  chmod 0755 ../helper/run_lint

  {
    echo "# sbopkglint $build_arch $build_package"
    echo '```'
    docker run --rm --platform "$platform" --entrypoint "$entrypoint" -v "$sbo":"$slackrepo" -v "$(dirname "$(pwd)")/helper/:/tmp/helper" aclemons/sbo-maintainer-tools:latest-$slackversion-$shortarch $arg -l -c "/tmp/helper/run_lint" || true
    rm -rf ../helper
    echo '```'
  } 2>&1 | sed 's/slackrepo/repo/g' | sed "/All tests passed/s/^\(.*\)$/✅ \1 ✅/" | sed "/\!\!\!/s/^\(.*\)$/⛔️ \1 ⛔️/" | tee ../lint_results
fi
